// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Image.ShoppingList
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// An API for creating and managing shopping list
    /// </summary>
    public partial interface IShoppingListAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Get all shopping list items
        /// </summary>
        /// <param name='shopperName'>
        /// Shopper name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetAllShoppingListItemsWithHttpMessagesAsync(string shopperName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create new shopping list item with request type POST
        /// </summary>
        /// <param name='shopperName'>
        /// Shopper name
        /// </param>
        /// <param name='title'>
        /// Shopping list item title
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PostShoppingListItemWithHttpMessagesAsync(string shopperName, ShoppingListTitleDto title = default(ShoppingListTitleDto), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get all pending shopping list items
        /// </summary>
        /// <param name='shopperName'>
        /// Shopper name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetPendingShoppingListItemsWithHttpMessagesAsync(string shopperName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get shopping list item
        /// </summary>
        /// <param name='shoppingListItemId'>
        /// Shopping list item identifier
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetShoppingListItemWithHttpMessagesAsync(System.Guid shoppingListItemId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete shopping list item
        /// </summary>
        /// <param name='shoppingListItemId'>
        /// Shopping list item identifier
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeleteShoppingListItemWithHttpMessagesAsync(System.Guid shoppingListItemId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create new shopping list item with request type PUT
        /// </summary>
        /// <param name='shopperName'>
        /// Shopper name
        /// </param>
        /// <param name='title'>
        /// Shopping list item title
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> SetShoppingListItemWithHttpMessagesAsync(string shopperName, string title, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update shopping list item in-cart value
        /// </summary>
        /// <param name='shoppingListItemId'>
        /// Shopping list item identifier
        /// </param>
        /// <param name='pending'>
        /// New shopping list item pending value
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> UpdateShoppingListItemPendingValueWithHttpMessagesAsync(System.Guid shoppingListItemId, bool pending, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete all unpending shopping list items
        /// </summary>
        /// <param name='shopperName'>
        /// Shopper name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DeleteAllUnpendingShoppingListItemsWithHttpMessagesAsync(string shopperName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create new shopper
        /// </summary>
        /// <param name='shopperName'>
        /// Shopper name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> CreateNewShopperWithHttpMessagesAsync(ShopperNameDto shopperName = default(ShopperNameDto), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
