// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Image.ShoppingList.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ErrorResult
    {
        /// <summary>
        /// Initializes a new instance of the ErrorResult class.
        /// </summary>
        public ErrorResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ErrorResult class.
        /// </summary>
        /// <param name="classification">Possible values include:
        /// 'InvalidArgument', 'EntityNotFound', 'UniqueConstraint',
        /// 'ReferenceConstraint', 'AuthenticationError', 'AuthorizationError',
        /// 'InvalidOperation', 'InternalError'</param>
        public ErrorResult(int? code = default(int?), string classification = default(string), string message = default(string))
        {
            Code = code;
            Classification = classification;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public int? Code { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'InvalidArgument',
        /// 'EntityNotFound', 'UniqueConstraint', 'ReferenceConstraint',
        /// 'AuthenticationError', 'AuthorizationError', 'InvalidOperation',
        /// 'InternalError'
        /// </summary>
        [JsonProperty(PropertyName = "Classification")]
        public string Classification { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

    }
}
