// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Image.ShoppingList.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ShoppingListItemResult
    {
        /// <summary>
        /// Initializes a new instance of the ShoppingListItemResult class.
        /// </summary>
        public ShoppingListItemResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ShoppingListItemResult class.
        /// </summary>
        public ShoppingListItemResult(System.Guid? id = default(System.Guid?), string title = default(string), string shopperName = default(string), bool? pending = default(bool?))
        {
            Id = id;
            Title = title;
            ShopperName = shopperName;
            Pending = pending;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShopperName")]
        public string ShopperName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Pending")]
        public bool? Pending { get; set; }

    }
}
